title: Gimli – A Static Homelab Startpage
email: gimli@geff.re
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theGeffrey
github_username:  geffreyvanderbos

# Build settings
theme: minima

# Load external sites like icons and Google Fonts. Set false to keep it local.
loadExternal: true 

# Change the colour the titlebar / addressbar gets in some browsers.
themeColor: 1F2126

# Enable light theme that switches with OS settings
automaticTheme: true

# Automatically open and give focus on the filter bar on page load
openFilterOnLoad: true

# Add a link of a background image, if you like.
backgroundImage:  https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1476&q=100
# Add your links here. The order stays the same.
# Find the names for the icons here: https://fonts.google.com/icons
# Google uses lowercase and underscore as spaces for icons.
# Icons only work when loadExternal is set to true.

links:
  - Name: Archivebox
    Description: Achiving the web
    URL: http://192.168.1.200:8112/
    # URL: \#
    Icon: archive
  
  - Name: Bookstack
    Description: Wiki for home and house
    URL: http://192.168.1.200:6875/
    Icon: menu_book
  
  - Name: Calibre Web
    Description: Manage my books and reading
    URL: http://192.168.1.200:8083/
    Icon: auto_stories
  
  - Name: Duplicati
    Description: Manage the backups
    URL: http://192.168.1.200:8200/
    Icon: backup

  - Name: File Browser
    Description: Browse files on Homelab
    URL: http://192.168.1.200:8151/
    Icon: folder_open

  - Name: Genexis Router
    Description: Access to the home router
    URL: http://192.168.1.245/
    Icon: router

  - Name: Ghostfolio
    Description: Stock and EFT management
    URL: http://192.168.1.200:3333/
    Icon: ssid_chart

  - Name: Homebox
    Description: Manage home inventory
    URL: http://192.168.1.200:3100/
    Icon: inventory

  - Name: Homebridge
    Description: Manage Apple Homekit devices
    URL: http://192.168.1.200:8581/
    Icon: account_tree

  - Name: Huginn
    Description: Webscrapers and notifiers
    URL: http://192.168.1.200:4750/
    Icon: circle_notifications

  - Name: Linkding
    Description: Bookmarking and read-it-later
    URL: http://192.168.1.200:9292/bookmarks
    Icon: bookmarks

  - Name: Mealie
    Description: All our meals and recipes
    URL: http://192.168.1.200:9925/
    Icon: dinner_dining

  - Name: Metube
    Description: Archive Youtube videos
    URL: http://192.168.1.200:8381/
    Icon: smart_display

  - Name: Muninn's Cockpit
    Description: See how server is doing
    URL: https://192.168.1.200:9090/
    Icon: analytics

  - Name: NGINX Proxy Manager
    Description: Edit proxy hosts
    URL: http://192.168.1.200:81/
    Icon: alt_route

  - Name: Paperless
    Description: Manage household documents
    URL: http://192.168.1.200:8111/
    Icon: folder

  - Name: PiHole
    Description: Local DNS and ad-blocker
    URL: http://192.168.1.200:8088/admin
    Icon: dns

  - Name: Portainer
    Description: Manage docker containers
    URL: http://192.168.1.200:9000//
    Icon: set_meal