title: Gimli – A Static Homelab Dashboard
email: gimli@geff.re
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theGeffrey
github_username:  geffreyvanderbos

# Build settings
theme: minima

# Load external sites like icons and Google Fonts. Set false to keep it local.
loadExternal: true 

# Change the colour the titlebar / addressbar gets in some browsers.
themeColor: 1F2126

# Add a link of a background image, if you like.
backgroundImage:  https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80
# https://images.unsplash.com/photo-1665672809651-229a937f4677?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1426&q=80
# https://images.unsplash.com/photo-1665824274860-621d2202f658?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80
# https://images.unsplash.com/photo-1665783734510-675749e54225?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=928&q=80

# Add your links here. The order stays the same. F
# ind the names for the icons here: https://fonts.google.com/icons
# Google uses lowercase and underscore as spaces for icons.
# Icons only work when loadExternal is set to true.

links:
  - Name: Archivebox
    Description: Achiving the web
    # URL: http://192.168.1.200:8112/
    URL: \#
    Icon: archive
  
  - Name: Bookstack
    Description: Wiki for home and house
    URL: http://192.168.1.200:6875/
    Icon: menu_book
  
  - Name: Calibre Web
    Description: Manage my books and reading
    URL: http://192.168.1.200:8083/
    Icon: auto_stories
  
  - Name: Duplicati
    Description: Manage the backups
    URL: http://192.168.1.200:8200/
    Icon: backup

  - Name: File Browser
    Description: Browse files on Homelab
    URL: http://192.168.1.200:8151/
    Icon: folder_open

  - Name: Genexis Router
    Description: Access to the home router
    URL: http://192.168.1.245/
    Icon: router

  - Name: Homebridge
    Description: Manage Apple Homekit devices
    URL: http://192.168.1.200:8581/
    Icon: account_tree

  - Name: Huginn
    Description: Webscrapers and notifiers
    URL: http://192.168.1.200:8581/
    Icon: circle_notifications

  - Name: Linkding
    Description: Bookmarking and read-it-later
    URL: http://192.168.1.200:9292/bookmarks
    Icon: bookmarks

  - Name: Mealie
    Description: All our meals and recipes
    URL: http://192.168.1.200:9925/
    Icon: dinner_dining

